name: build
on: push
jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.2
            gemfile: Gemfile
          - ruby: 3.0
            gemfile: gemfiles/Gemfile-7-0
          - ruby: 2.7
            gemfile: gemfiles/Gemfile-6-1
          - ruby: 2.6
            gemfile: gemfiles/Gemfile-6-0
          - ruby: 2.5
            gemfile: gemfiles/Gemfile-5-2
          - ruby: 2.5
            gemfile: gemfiles/Gemfile-5-1
          - ruby: 2.5
            gemfile: gemfiles/Gemfile-5-0
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      USE_OFFICIAL_GEM_SOURCE: 1
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 10
      - run: createdb dummy_test
      - run: bundle exec rails db:migrate
      - name: Run tests
        run: bundle exec rails test
